version: 2
updates:
  # Main project dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - "jimmypocock"

  # CDK dependencies  
  - package-ecosystem: "npm"
    directory: "/cdk"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "jimmypocock"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    assignees:
      - "jimmypocock"