#!/bin/bash
# Analyze moderation Lambda logs

echo "🔍 Analyzing Moderation Lambda logs..."
echo ""
echo "Run these commands to find issues:"
echo ""
echo "1. Find ERROR messages:"
echo "aws logs filter-log-events \\"
echo "  --log-group-name '/aws/lambda/gravy-prompts-production-ModerateContentFunction*' \\"
echo "  --filter-pattern 'ERROR' \\"
echo "  --start-time \$(date -u -d '1 hour ago' +%s000) \\"
echo "  --query 'events[*].[timestamp,message]' \\"
echo "  --output text"
echo ""
echo "2. Find Comprehend errors:"
echo "aws logs filter-log-events \\"
echo "  --log-group-name '/aws/lambda/gravy-prompts-production-ModerateContentFunction*' \\"
echo "  --filter-pattern 'Comprehend' \\"
echo "  --start-time \$(date -u -d '1 hour ago' +%s000) \\"
echo "  --query 'events[*].message' \\"
echo "  --output text | grep -i error"
echo ""
echo "3. Check for infinite loops (same templateId repeated):"
echo "aws logs filter-log-events \\"
echo "  --log-group-name '/aws/lambda/gravy-prompts-production-ModerateContentFunction*' \\"
echo "  --filter-pattern 'Starting moderation for template' \\"
echo "  --start-time \$(date -u -d '1 hour ago' +%s000) \\"
echo "  --query 'events[*].message' \\"
echo "  --output text | sort | uniq -c | sort -nr"
echo ""
echo "4. Find successful moderation completions:"
echo "aws logs filter-log-events \\"
echo "  --log-group-name '/aws/lambda/gravy-prompts-production-ModerateContentFunction*' \\"
echo "  --filter-pattern 'Successfully updated moderation' \\"
echo "  --start-time \$(date -u -d '1 hour ago' +%s000) \\"
echo "  --query 'events[*].message' \\"
echo "  --output text"
echo ""
echo "5. Check for rate limiting or throttling:"
echo "aws logs filter-log-events \\"
echo "  --log-group-name '/aws/lambda/gravy-prompts-production-ModerateContentFunction*' \\"
echo "  --filter-pattern '[Throttl,Rate,Limit]' \\"
echo "  --start-time \$(date -u -d '1 hour ago' +%s000) \\"
echo "  --query 'events[*].message' \\"
echo "  --output text"